# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Pascal Wallenius
site_url: https://pwalleni.github.io
repo_url: https://github.com/pwalleni/pwalleni.github.io

theme:
  name: material

plugins:
  - search
  - tags:
      tags_file: tags.md
